require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "c",
        "go",
        "vim",
        "cpp",
        "zig",
        "lua",
        "nix",
        "help",
        "rust",
        "llvm",
        "glsl",
        "norg",
        "bash",
        "make",
        "vala",
        "fish",
        "latex",
        "ocaml",
        "meson",
        "python",
        "scheme",
        "fennel",
        "elixir",
        "sxhkdrc",
        "haskell",
        "clojure",
        "markdown",
        "gitignore",
        "commonlisp",
        "javascript",
        "typescript",
    },
    highlight = {
        enable = true,
    },
    indent = {
        enable = true,
    },
})
